# Generated by Django 4.2.1 on 2023-12-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_category_options_equipment_manufacture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='name_filter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.namefilter', verbose_name='Название дополнительного фильтра: '),
        ),
        migrations.AddField(
            model_name='equipment',
            name='value_filter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.filtervalue', verbose_name='Значение фильтра: '),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='equipment.category', verbose_name='Тип оборудования: '),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacture',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.equipmentmanufacturer', verbose_name='Производитель'),
        ),
    ]
