# Generated by Django 4.2.1 on 2023-12-13 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipment_name_filter_equipment_value_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name_filter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.namefilter', verbose_name='Название дополнительного фильтра: '),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='value_filter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.filtervalue', verbose_name='Значение фильтра: '),
        ),
    ]
