# Generated by Django 4.2.1 on 2023-12-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_alter_equipment_name_filter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='is_available',
        ),
    ]
