# Generated by Django 4.2.1 on 2023-12-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_remove_equipment_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='В наличие'),
        ),
    ]
