# Generated by Django 4.2.1 on 2023-12-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_equipment_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'verbose_name': 'Назначение', 'verbose_name_plural': 'Назначение'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='targ',
        ),
    ]
