# Generated by Django 4.2.1 on 2024-01-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_alter_target_options_remove_category_targ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.category', verbose_name='Тип оборудования: '),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='tar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.target', verbose_name='Назначение: '),
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Время работы тестировщиков: ')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workinghours', to='equipment.servicecenters', verbose_name='Сервисный центр: ')),
            ],
            options={
                'verbose_name': 'Время работы тестировщиков',
                'verbose_name_plural': 'Время работы тестировщиков',
            },
        ),
    ]
